//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.10.11 at 12:20:15 AM CDT 
//


package com.eb.publisher.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="url-publish" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="topicid" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="urltitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="urlclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "urlPublish"
})
@XmlRootElement(name = "publish-list")
public class PublishList {

    @XmlElement(name = "url-publish", required = true)
    protected List<PublishList.UrlPublish> urlPublish;

    /**
     * Gets the value of the urlPublish property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the urlPublish property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUrlPublish().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublishList.UrlPublish }
     * 
     * 
     */
    public List<PublishList.UrlPublish> getUrlPublish() {
        if (urlPublish == null) {
            urlPublish = new ArrayList<PublishList.UrlPublish>();
        }
        return this.urlPublish;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="topicid" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="urltitle" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="urlclass" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "topicid",
        "urltitle",
        "urlclass"
    })
    public static class UrlPublish {

        protected int topicid;
        @XmlElement(required = true)
        protected String urltitle;
        @XmlElement(required = true)
        protected String urlclass;

        /**
         * Gets the value of the topicid property.
         * 
         */
        public int getTopicid() {
            return topicid;
        }

        /**
         * Sets the value of the topicid property.
         * 
         */
        public void setTopicid(int value) {
            this.topicid = value;
        }

        /**
         * Gets the value of the urltitle property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrltitle() {
            return urltitle;
        }

        /**
         * Sets the value of the urltitle property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrltitle(String value) {
            this.urltitle = value;
        }

        /**
         * Gets the value of the urlclass property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUrlclass() {
            return urlclass;
        }

        /**
         * Sets the value of the urlclass property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUrlclass(String value) {
            this.urlclass = value;
        }

    }

}
